services:
  db:
    image: postgres:16
    container_name: timegrid_db
    environment:
      POSTGRES_USER: timegrid
      POSTGRES_PASSWORD: timegrid
      POSTGRES_DB: timegrid
    ports:
      - "5432:5432"
    volumes:
      - timegrid_pg:/var/lib/postgresql/data

volumes:
  timegrid_pg:
